services:
  db:
    image: postgres:16
    container_name: fenja_postgres
    environment:
      POSTGRES_USER: fenja
      POSTGRES_PASSWORD: fenja
      POSTGRES_DB: fenja_health
    ports:
      - "5432:5432"
    volumes:
      - fenja_pgdata:/var/lib/postgresql/data

volumes:
  fenja_pgdata:
